version: "3.5"
services:
    redis:
        container_name: redis
        image: "redis:alpine"
        environment:
            TZ: Asia/Shanghai
        restart: always
        expose:
            - "6379"
    mysql:
        container_name: mysql
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
        restart: always
        environment:
            TZ: Asia/Shanghai
            MYSQL_DATABASE: 'fastapi'
            MYSQL_USER: 'fastapi'
            MYSQL_PASSWORD: 'fastapi'
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        expose:
            - "3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./my.cnf:/etc/my.cnf
    apps:
        container_name: apps
        build: .
        restart: always
        environment:
            TZ: Asia/Shanghai
        expose:
            - "8000"
        volumes:
            - ./backend:/backend
        depends_on:
            - redis
            - mysql
            
    nginx:
        container_name: nginx
        image: nginx:1.19.0-alpine
        restart: always
        environment:
            TZ: Asia/Shanghai
        ports:
            - target: 80
              published: 80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/var/www/html
        depends_on:
            - apps